cloud-gov/deploy-bosh

- credentials.example.yml
- pipeline.yml
- Don't make tooling dependent on staging
- Go ahead and reference git repos directly
- Reference AWS bits directly for CPI and stemcell
Fixes 18F/cg-atlas#31
> Simplify the pipeline and credentials

- bosh-deployment.yml
This should fix our issue with ephemeral disk encryption and also allow us to use new features as they come to the CPI.
> Tell bosh to use aws_cpi and clean up manifest

- bosh-deployment.yml
- secrets.example.yml
This won't have any effect until https://github.com/cloudfoundry/bosh/pull/1337 is merged and we update bosh. After that, this patch should forward health monitor alerts and heartbeats to riemann.
Part of https://github.com/18F/cg-product/issues/17.
Question for @sharms and @LinuxBozo: when we set up the secrets, I assume we'll have staging bosh send riemann alerts to 0.monitoring.monitoring.monitoring-staging.bosh and production bosh send to 0.monitoring.monitoring.monitoring-prod.bosh. But what about tooling bosh? Our [VPC diagram](https://docs.google.com/drawings/d/1X1GZ664sjG5_JQ0Wpco430X_lK2Ozv-tgl5Wel9Je_g/edit?ts=5750a7f4) has a riemann instance in tooling, but I don't see that in govcloud. Should we add a riemann instance in the tooling vpc so tooling bosh has somewhere to send …
> Configure health monitor riemann plugin.

- bosh-deployment.yml
- hardening scripts from fisma
- tripwire agent
- nessus-agent
- newrelic monitoring
- riemann client
- clamav
- snort
> Add jobs to bosh deployments:

- bosh-deployment.yml
So that we can drop blobstore buckets from encrypt-blobstore and enable mandatory encryption on blobstore buckets.
> Encrypt blobstore uploads.

- pipeline.yml
Our changes are [now in upstream](https://github.com/cloudfoundry-community/cron-boshrelease/pull/3#issuecomment-261275326) so we can drop our fork 🎉
> Use the upstream cron release from bosh.io

- bosh-deployment.yml
- bosh-init-deployment.yml
A nist AU-8 update to the NTP urls to use NIST timeservers as our `SYNCHRONIZATION WITH AUTHORITATIVE TIME SOURCE`
http://tf.nist.gov/tf-cgi/servers.cgi
> Update ntp server for AU-8

- cronjobs/unknown-vms.sh
This PR extends the `unknown-vms` cron job to emit a metric for each IaaS instance with it's uptime.  
These metrics will be used by riemann to know which systems must be monitored for active log activity for  https://github.com/18F/cg-product/issues/476
> [WIP] Emit uptime metrics for all non-whitelisted VMs

- bosh-init-deployment.yml
- bosh-init-secrets.example.yml
- secrets.example.yml
Because bosh doesn't use or package it anymore. h/t @LinuxBozo
> Drop redis from master-bosh config.

- update-runtime-config.sh
Because our releases include versions wrapped in both single and double quotes--not sure why.
```
root@d3bc6a93-0fcf-48ed-5c89-5b7eb3e7d8da:/tmp/build/59447205# grep -R "^version" releases
releases/fisma/release.MF:version: '15'
releases/tripwire/release.MF:version: '16'
releases/awslogs/release.MF:version: "17"
releases/nessus-agent/release.MF:version: '15'
releases/newrelic/release.MF:version: '15'
releases/clamav/release.MF:version: '7'
releases/snort/release.MF:version: '47'
releases/riemannc/release.MF:version: "9"
releases/riemann/release.MF:version: 0.16.83
releases/collectd/release.MF:version: '14'
releases/cron/release.MF:version: 1.1.1
```
> Drop single and double quotes from release versions.

- bosh-deployment.yml
- runtime-config.yml
- update-runtime-config.yml
Removing cron from the addons configuration for bosh deployments. This means we'll need to bring them back in the repos that use them. Those PRs are cross-linked below. 👇 
🎩 💁‍♂️ to @cnelson and this [Github search query](https://github.com/search?l=YAML&p=2&q=user%3A18F+cron%3A&ref=searchresults&type=Code&utf8=%E2%9C%93).
> Remove addons related to cron

- pipeline.yml
So that concourse notices when the opslogin uaa clients change.
> Update bosh config paths.

- cloud-config/cloud-config-main.yml
Add cloud config for logsearch (and start of kubernetes) deployments.
Goes with https://github.com/18F/cg-deploy-logsearch/pull/66
> [WIP] add cloud config for logsearch

- cloud-config/cloud-config-main.yml
Logsearch network in cloud config needs to point to services subnet.
Goes with https://github.com/18F/cg-provision/pull/260
> move logsearch network to services

- bosh-create-env-deployment.yml
Because it got renamed upstream.
> Rename postgres job to latest.

- cloud-config/cloud-config-main.yml
Rename logsearch network to something we can use for all deployments in services subnet
PR to update logsearch deployment: https://github.com/18F/cg-deploy-logsearch/pull/71
> Rename logsearch network to services

- credentials.example.yml
- pipeline.yml
Note: this adds a dependency on governmentpaas/semver-resource for instance profiles. If we don't want to depend on the gds fork, we can make our own.
> Drop aws credentials.

- cloud-config/cloud-config-main.yml
I think we should change the instance type from 4 vCPU/7.5GB RAM to 2 vCPUs/15GB RAM.
The elasticsearch instance running on the parser has been consuming more memory since moving to ES5.X, frequently using > 90% of memory, and occasionally starting to swap, however the CPU usage does not climb above 20%: 
Swapping CPUs for more memory and saving ~ $1400/yr seems like the right approach to me
> Align parser instance type with workload

- cloud-config/cloud-config-tooling.yml
Decided to make this permanent;  Even with retention policy being properly applied, we are still > 170GB
> Bump influxdb disk

- cronjobs/unknown-vms.sh
Should allow for better correlation to the bosh instance where this fired.
Also, increase TTL as we add more VMs to scale the platform
> Capture the bosh instance this check belongs to better

- cloud-config/cloud-config-development.yml
Because nodes are constantly getting hosed on development.
> Revert to default kubernetes instance types on development.

- releases/releases.yml
Standardize on 18F forks of logsearch releases. We should still decide how we're going to keep these up to date.
> Build logsearch bosh releases.

- cloud-config/cloud-config-development.yml
- cloud-config/cloud-config-main.yml
Goes with https://github.com/18F/cg-deploy-logsearch/pull/83.
* Drop unused vm type
* Add ingestor persistent disk
> Update logsearch cloud config for latest releases.

- cloud-config/cloud-config-main.yml
Note: don't merge until logstash persistent queues are deployed on production.
> Delete and resize logsearch resources after upgrade.

- releases/releases.yml
Goes with https://github.com/18F/cg-secureproxy-boshrelease/pull/19.
> Build secureproxy in its own pipeline.

- bosh-deployment.yml
Separate whitelist into bosh director and instance whitelist, so that bosh director isn't ignored twice.
> Drop duplicate bosh director from whitelist.

- cronjobs/unknown-vms.sh
The prometheus push gateway caches the most recent metric indefinitely,
so metrics for instances that have been deleted persist forever. To fix,
this patch deletes cached metrics for the given vpc before pushing.
> Clear cached messages from gateway before push.

- cloud-config/cloud-config-main.yml
- cloud-config/cloud-config-tooling.yml
* Bump kubernetes ephemeral disk to make room for packages
* Drop concourse and bosh disks because they're mostly unused
> Update miscellaneous disk sizes.

- pipeline.yml
Because the deprecation warning about specifying both `file` and `config` on a task is now a deprecation error. Depends on https://github.com/18F/cg-pipeline-tasks/pull/57.
> Fix concourse deprecation error.

- bosh-deployment.yml
Reverts 18F/cg-deploy-bosh#181
> Multiple ci jobs use a shared uaa client to auth to bosh, and it looks like they're invalidating each others' tokens.
> Revert "Enable uniqueness restriction on refresh tokens."

- pipeline.yml
Because password authentication to tooling bosh doesn't appear to work after switching to the latest bosh-deployment-resource.
> Authenticate to bosh using uaa client credentials.

- bosh-deployment.yml
Since bosh is deployed from another bosh, it won't know about itself during the VM check, so make sure we ignore it. Also, always ignore masterbosh, since we know it will exist and isn't tracked by another bosh.
> Ignore masterbosh and the main VPC bosh in the unknown vm check

- pipeline.yml
- releases/releases.yml
- runtime-config/base.yml
- update-runtime-config-tooling.yml
- update-runtime-config.yml
Because we're only using this to report system metrics we already get from bosh health monitor and collectd. Note: we'll continue using new relic for specific applications, just not on every bosh vm.
> Stop running new relic agent on every host.

- bosh-deployment.yml
This hasn't been working for a while, and it's already covered by prometheus. It's also sending millions of error logs per day. Let's drop it.
> Drop riemann health monitor plugin.

- cloud-config/cloud-config-tooling.yml
At 900 we still are entering rushed storage mode and dropping ~hundreds
> Increase piops to 14000 to handle metric load

- cloud-config/cloud-config-development.yml
- cloud-config/cloud-config-staging.yml
Save money on instances we hardly use.
> Drop instance types on development and staging.

- cloud-config/cf.yml
- cloud-config/cloud-config-base.yml
- cloud-config/cloud-config-main.yml
- cloud-config/cloud-config-master.yml
- cloud-config/cloud-config-tooling.yml
EBS volumes use gp2 by default (hard-coded in BOSH) and are encrypted by default (set in https://github.com/18F/cg-deploy-bosh/blob/master/bosh-deployment.yml#L251). We shouldn't need to copy default properties to each disk anymore.
> Disks are encrypted by default.

- cloud-config/main.yml
Avoid `IP address not available for the link provider` warnings on cf-deployment.
> Set default network to manual.

- cloud-config/cf.yml
To restore *.18f.gov routes after migration to cf-deployment.
> Add vm extension for *.18f.gov client elb.

- cloud-config/cf.yml
Because diego cells are running out of (allocated) disk.
> Add 200gb ephemeral disk extension.

- cloud-config/master.yml
Removes conflicts for compilation VMs when compiling toolingbosh packages from masterbosh.
> Make sure DNS private ips are in masterbosh reserve block

- releases/releases.yml
Revert after upstream accepts prometheus 2.x patch.
> Temporarily build prometheus release.

- releases/releases.yml
We're using the grafana release bundled with prometheus-boshrelease now.
> Stop building custom grafana release.

- ci/pipeline.yml
- cloud-config/cf.yml
- cloud-config/main.yml
- cloud-config/master.yml
- cloud-config/production.yml
- cloud-config/tooling.yml
After https://github.com/18F/cg-provision/pull/382 is merged and DNS points to ALBs, we can drop public-facing ELBs from VM extensions. Don't merge until DNS is updated!
> [WIP] Balance behind ALBs but not ELBs.

- releases/releases.yml
* Use upstream prometheus
* Use temporary fix for oauth2 proxy
> Update bosh release branches.

- ci/pipeline.yml
Now that upstream has moved blobstore tls and bpm into the base
manifest, we can drop the experimental opsfiles from our concourse
pipeline.
> Revert experimental blobstore and bpm opsfiles.

- ci/pipeline.yml
- operations/releases.yml
Now that bosh-deployment includes source release opsfiles, we can delegate release versions to upstream while still deploying the latest stemcell. More details in https://github.com/cloudfoundry/bosh-deployment/issues/180.
> Use upstream release versions.

- releases/releases.yml
Looks like I added this release to the pipeline while I was testing it out and then rolled it back. This is pointing to a fork at the moment, because upstream didn't check in a `releases` directory, which our release builder requires. We can ask upstream to check in releases, or move the fork to 18F, or allow our builder to handle releases without a `releases` directory. WDYT @LinuxBozo ?
> [WIP] Build elasticache broker release.

- ci/pipeline.yml
- operations/releases.yml
Now that upstream bosh-deployment has updated its bosh release version,
we can stop pinning versions here.
> Revert to upstream bosh release.

- operations/cron.yml
Now that we're using managed nat gateways instead of nat instances, nat
services won't show up in our ec2 instance list and don't need to be
whitelisted.
> Drop nat ips from instance whitelist.

- ci/pipeline.yml
- operations/name.yml
- operations/toolingbosh-tld.yml
Should result in no deployment diffs.
> Standardize ops files across deployments.

- ci/pipeline.yml
- ci/update-runtime-config.sh
- ci/update-runtime-config.yml
- operations/dns.yml
- operations/kubernetes-dns.yml
Part of migration for https://github.com/cloudfoundry/cf-deployment/releases/tag/v3.0.0. Goes with https://github.com/18F/cg-deploy-cf/pull/367.
> [WIP] Dns runtime config

- ci/update-runtime-config.sh
- operations/kubernetes-dns.yml
Now that https://github.com/cloudfoundry/bosh-dns-aliases-release/pull/5
has been released, we can configure kubernetes dns handlers on
individual deployments.
> Drop kubernetes dns handler.

- operations/cron.yml
- variables/development.yml
- variables/production.yml
- variables/staging.yml
- variables/tooling.yml
* Use prometheus dns aliases for dev/stage/prod bosh
* Look up prometheus address via bosh db for tooling bosh
> Fix push gateway dns in unknown vms checks.

- operations/cron.yml
Fixes extra whitespace in psql query result.
> Set --no-align flag to trim whitespace from tuple.

- cloud-config/tooling.yml
This is arbitrary. We resized these down 11 months ago from 30 GB to
16GB and then our alerting started complaining about 70% disk full. At
20GB, for the past 4 hours, it's been steady at 63% full on production.
Based on this limited research, I'm digging this middle ground of 20GB
instead of 16GB.
> Resize BOSH disks up to 20GB

- ci/pipeline.yml
- operations/source-release-credhub.yml
This should solve any issues with pre-compiled credhub releases based on xenial now that upstream has switched to xenial as default stemcell.
> Use credhub bosh.io release instead of pre-compiled from upstream

- cloud-config/development.yml
- cloud-config/main.yml
After fixing up clamav scan on access, we have lots of new data, and we never adjusted disk sizes. Rectify this.
> Update disk size for logsearch-platform

- ci/update-cloud-config-tooling-development.yml
- ci/update-cloud-config.yml
- ci/update-runtime-config.yml
This behavior has been deprecated since 4.1.0 and will eventually cause an error in later Concourse versions.
https://concourse-ci.org/download.html#v410
> Add in necessary params

- cloud-config/tooling.yml
We ~~argue~~ bikeshed about this on the reg here, https://gsa-tts.slack.com/archives/C0ENP71UG/p1537372483000100
**What do y'all think?** Is 40GB enough? That doubles the diskspace and the SWAP. Should we keep SWAP at 10GB instead of the default? 50% of whatever the diskspace is?
> Double the disk space for BOSH VMs

- ci/pipeline.yml
- releases/releases.yml
Bugfix needed: https://github.com/cloudfoundry-community/cron-boshrelease/pull/8
Last known upstream release details:
```
cron BOSH Release v1.1.3
@starkandwayne-bot starkandwayne-bot released this on Jan 27, 2017 
5 commits to master since this release
```
> Use our own cron release until upstream does release with bugfix

- releases/releases.yml
This will pickup any tags that start `trusty-` for `awslogs`. This is the old Trusty compatible version of `awslogs-boshrelease`. The new version will be named `awslogs-xenial` and will be added in a PR later on. To ensure this tag exists, checkout [the `cg-awslogs-boshrelease` repo](https://github.com/18F/cg-awslogs-boshrelease) under [tags](https://github.com/18F/cg-awslogs-boshrelease/tags).
> Add tag_filter to lock-in Trusty

- releases/releases.yml
This is so we can continue forking our code for both Xenial and Trusty
with minimal confusion. The docs explaining this exist in the
`cg-awslogs-boshrelease` [repository](https://github.com/18F/cg-awslogs-boshrelease).
> Rename the base branch for Trusty

- releases/releases.yml
Currently a _work in progress_, eventually this boshrelease will be working off of `master` and not some arbitrary branch e.g. `upgrade-to-xenial`.
> [wip] Add awslogs-xenial boshrelease

- ci/pipeline.yml
- ci/update-runtime-config.yml
- operations/cron.yml
- runtime-config/runtime.yml
This patch also adds awslogs-xenial to the development pipeline jobs as
well.
**I have done the following**
- Flown the pipeline here with these changes
- Allowed the upload of two different awslogs to the development BOSH
- Renamed the awslogs resource to awslogs-trusty resource to avoid any weird naming issues in Concourse
- Created an awslogs-xenial resource that is being used for development BOSH
> Rename awslogs to &-trusty everywhere

- cloud-config/main.yml
**do not merge this yet**
This should alleviate the disk issues we've seen in production about disks being at 70% for logsearch-platform in production. Pairing with @jontours on this.
> Resize disks up to 3.5T for logsearch-platform

- operations/external-db.yml
- operations/source-release-credhub.yml
Abides by `mode` parameter to limit cred generation iff that cred exists.  @rogeruiz let's wait to merge until CF creds are rotated for this round.
> Bump CH version and fix ops file for external-db

- runtime-config/runtime.yml
this is due to https://www.pivotaltracker.com/story/show/167907044/comments/205808093, and should fix builds failing with this error:
`Error: Addon 'hardening' specifies 'properties' which is not supported. 'properties' are only allowed in the 'jobs' array`
> remove deprecated properties block from addon, add to jobs

- operations/s3-blobstore.yml
Following along the instructions in cloudfoundry/bosh-deployment#254
We need to set the blobstore config on the agent, rather than just removing it due to bosh API change.
> set s3 config on bosh agents

- operations/s3-blobstore.yml
[this commit](https://github.com/cloudfoundry/bosh/commit/b2383dfc2f147d8cafe61323ea8d9157979ba881#diff-99e4eca64232c4ddfa30b3b73740f315) is causing our config to fail validation. This is an attempt at a workaround while we work with the upstream to patch it.
> set access_key_id and secret_access_key as an attempted workaround

- ci/pipeline.yml
This will hopefully allow us to deploy credhub across a wider variety of stemcells, getting us unstuck on pinning other versions periodically.
> use source release for credhub in dev

- ci/pipeline.yml
- operations/credhub-source.yml
using the opsfile from bosh-deployment still leaves us stuck with bosh and credhub versions pinned together. this should separate them
> supply our own opsfile for credhub

- cloud-config/staging.yml
Logsearch in staging is failing due to overfull disks. This doubles the disk size, which should fix it.
> bigger logsearch disks

- ci/pipeline.yml
This just makes much more sense.
> move runtime config updates to deployment step.

- ci/pipeline.yml
This reverts commit 3ea0c529d487ad52e94fe2e8e6ebbbc2fd058069.
I was wrong on the order for many reasons.
> Revert "move runtime config updates to deployment step."

- cloud-config/development.yml
logsearch-platform-development isn't deploying because it can't allocate all its shards because it lacks disk space. This should fix it. 
none - this is a dev scaling operation
> bigger disks for logsearch-platform in dev

- ci/pipeline.yml
I missed adding the env name to tooling. This fixes it
None.
> add env name to tooling

- ci/update-runtime-config.sh
This unpins the FISMA release in production and tooling. It's been soaking for a week and seems fine.
this should improve our security posture
> release FISMA release

- releases/releases.yml
the branches `wip` and `master` on 18F/cf-domain-broker-alb-boshrelease are identical, so we should build master rather than wip
None
> correct domain broker branch

- cloud-config/tooling.yml
This fixes the LB group for doomsday. Manually tested and it works as intended.
None.
> tooling: map doomsday lb group to vm extension.

- ci/pipeline.yml
- operations/reserved-ips.yml
We're not putting aws-managed services (e.g. ELBs) into different subnets from bosh, so sometimes AWS assigns them an IP address that gets in the way. This lets us tell bosh about these addresses (in the services network, at least) so we can avoid errors like `Error: Unknown CPI error 'Unknown' with message 'Address  <ip address> is in use.' in 'create_vm' CPI method `
None
> workaround for ignoring IP addresses dynamically assigned by AWS

- cloud-config/reserved-ips.yml
networks is a list, not a hash, so we need to get the services network by name
None.
> find network to modify by name

- ci/pipeline.yml
- cloud-config/reserved-ips.yml
These changes aren't working nicely, and they're a workaround for a thing we _think_ we can fix properly
None
> undo reserved ip changes

- ci/pipeline.yml
Remove vars file in favour of Credhub for https://github.com/18F/cg-product/issues/1211.
Build [#1237](https://ci.fr.cloud.gov/teams/main/pipelines/deploy-bosh/jobs/deploy-development-bosh/builds/1237)
> removing vars store.

- ci/pipeline.yml
Removed vars file in favour of Credhub integration. Part of https://github.com/18F/cg-product/issues/1213.
Build [#1207](https://ci.fr.cloud.gov/teams/main/pipelines/deploy-bosh/jobs/deploy-staging-bosh/builds/1207)
> removed vars file from staging bosh.

- ci/pipeline.yml
This lets us pin the tripwire release and test new versions in dev
None
> separate tripwire release resource for dev

- ci/pipeline.yml
In my last PR screwed up the resource name in dev. This fixes it.
None
> fix resource name

- ci/pipeline.yml
- remove vars files
Read from credhub instead of a vars file.
> removed vars files for prod bosh

- operations/uaa-clients.yml
- add the clients via deployment manifest instead of manually.
Just makes it more repeatable. There is no way to limit the scope to just `credhub.read`, that currently fails, so `credhub.write` must also be granted.
> added doomsday-clients.

- bosh-create-env.sh
- operations/credhub-source.yml
- get rid of credhub lock.
- use the formal ops files for source releases.
Just updates.
> get on source releases.

- bosh-create-env.sh
- ci/pipeline.yml
- I accidentally removed the UAA and Credhub integration in a previous deployment via https://github.com/18F/cg-deploy-bosh/commit/60b5c040ff4fe4e6ea35543a0b12bb3918ac144c, which is bad. This undoes that.
- And removed an extra line in the pipeline config, lol.
None.
> fixed bad deployment config.

- README.md
- cloud-config/base.yml
- generate-instance-config.sh
- seeded the base cloud config with all us-gov-west-1 instance types.
This doesn't change any instance types, just makes the instance types AWS offers available under their type name to all bosh deployments, so it's both easier to understand deployed instance types and ensure that all instances are available without having to piecemeal configuration changes.
This is to help make the cost/resourcing changes easier to both understand and work with.
None, just an AWS configuration reference.
> new instances.

- operations/update.yml
- defaults to 3, updating to 8 so we can do more at once.
None.
> increased parallel worker count to 8.

- operations/update.yml
- This reverts commit 832d5971df20c13be7c1ac4ba44f5f31e5e94d65, reversing
changes made to 3690a2c8c97a8596e4c2eecd55badeda6c466ec2.
- reverts #411 because apparently there are no default for some of the fields:
- broken build [#1252](https://ci.fr.cloud.gov/teams/main/pipelines/deploy-bosh/jobs/deploy-staging-bosh/builds/1252)
None.
> Revert "Merge pull request #411 from 18F/all/worker-count"

- ci/pipeline.yml
- operations/max-tasks.yml
- Update `director.max_tasks` value from default of 2000 to 200 (10%)
- Update pipeline to use new ops file
None
Signed-off-by: Chris McGowan (christopher.r.mcgowan@gsa.gov)
> Adding in new ops file to limit max tasks to 200 from default 2000 to save disk space

- ci/pipeline.yml
- Refactor the pipeline to be linear.
- Remove the semver resource (wasn't used anywhere).
- Added groups for humans.
- Reorder the jobs in the pipeline configuration file to be top -> bottom job order to match left -> right visual order, because it's easier for humans.
- Everything is now an auto-trigger because that's good CI principles.
- Common releases are now environment locked.
- Deleted the development-specific references in favour of trunk-based development.
You can see a reference on the [deploy-bosh-test pipeline](https://ci.fr.cloud.gov/teams/main/pipelines/deploy-bosh-test) (please don't unpause it, just for visual reference).
None, functional change.
> linear pipeline refactor

- operations/cron.yml
Currently, we get a false alerts multiple times a day for this. I think it's a timing issue, and the thinking here is that:
- psql calls are fast
- aws-cli calls are very slow
- bosh must update its database _after_ an instance is created
So, by putting the psql call after the awscli call, we should reduce or eliminate the false alarms.
Should reduce alert fatigue about this alert, making us more secure.
> reorder commands to reduce timing issues

- releases/releases.yml
- remove releases we no longer use
- move off of jmcarp's fork for admin-ui, since it's now even with the upstream
None
> remove unused releases

- runtime-config/runtime.yml
- add aide to all bosh instances via runtime config
- remove tripwire from all bosh releases
No immediate considerations. This is a step towards moving to AIDE, which should improve our security posture.
> replace tripwire with AIDE

- cloud-config/cf.yml
- Adding in a 250 gb disk size for diego-cells
- Prelim for ticket: https://github.com/cloud-gov/cg-deploy-cf/issues/492
N/A
> adding to cloud config for 250 diego cell disk size

- cloud-config/tooling.yml
We are starting to receive alerts that the disk space is filling up in our BOSH instances.  This changeset increases the available disk space by 15%.
- Increase disk size by 15% to 92,000 in the tooling BOSH configuration so it flows to the rest of the BOSH instances
None; this is a configuration adjustment of our open source infrastructure.
> Increase disk size for BOSH

- cloud-config/main.yml
- Increase the base logsearch data persistent disk from 3.5 to 7 TB
n/a
> Doubling logsearch data disk from 3.5 to 7 TB

- releases/releases.yml
- Remove logsearch and logsearch-for-cloudfoundry releases to move them to https://github.com/cloud-gov/cg-deploy-logsearch in order to support adding testing tasks to deployment
None
> Remove logsearch and logsearch-for-cloudfoundry releases

- cloud-config/tooling.yml
Adds the credhub security group to the concourse network.
This opens the credhub ports to ingress traffic.
> add credhub security group to concourse network

- operations/cron.yml
- Update path for cron ops file to use new aws-logs bionic release
- Proper check of bosh instances inside the VPCs once director moves to bionic
> fixing old awslogs path

- cloud-config/tooling.yml
- Create 5 GB disk type to support moving doomsday persistent storage to it's own disk
N/A
> Adding new disk type for doomsday in tooling

- ci/pipeline.yml
- ci/update-runtime-config.yml
- releases/releases.yml
- runtime-config/runtime.yml
- Remove logic in runtime config template to select correct awslogs release since we no longer run xenial stemcells
- Remove awslog-xenial release build pipeline
- Remove awslog-xenial release from runtime and bosh releases
n/a
> cleanup awslogs-xenial release

- cloud-config/cf.yml
- add tcp security group to tcp-routers
Allows greater network access, but it's necessary access
> add tcp security group to tcp-routers

- operations/masterbosh-ntp.yml
- Add temp ops entry to move PG job default to PG-10 to migrate DB schema to allow newer versions of PG later
Staying current to allow us to follow bosh-deployment and keep patched
> temp add ops entry to migrate PG to PG10 first

- operations/external-db.yml
- Modify internal external db ops file to now remove default PG job
Allows CG to continue to use bosh deployment to keep BOSH current
> adding ops entry to remove default pg job

- cloud-config/cf.yml
Updates to support https://github.com/cloud-gov/product/issues/2339
- Bumps cf ephemeral disk to 300GB from 250GB
None
> chore: Bump cf ephemeral disk config to 300GB

- empty-vm.yml
- runtime-config/runtime.yml
- Moved harden to include bionic only
- Added harden for jammy
- Add base vm deployment
None.
> Updating runtime to exclude jammy for now

- runtime-config/runtime.yml
Closes https://github.com/cloud-gov/product/issues/2398
After testing/verifying that AIDE runs properly on a VM built on Ubuntu Jammy, we are adding AIDE to the list of jobs deployed on all VMs in the runtime config for Ubuntu Jammy
None
> add aide release/job to jammy runtime config

- runtime-config/runtime.yml
[After testing and confirmed that the cg-harden-boshrelease compiles and deploys successfully on the Ubuntu Jammy runtime](https://github.com/cloud-gov/product/issues/2404), we are adding it to the runtime config so that any VM deployed on the Ubuntu Jammy stemcell will include that release
Closes https://github.com/cloud-gov/product/issues/2404
None
> add FISMA release to jammy runtime

- ci/pipeline.yml
- ci/update-runtime-config.yml
- runtime-config/runtime.yml
Related to https://github.com/cloud-gov/product/issues/2397
- Add awslogs-jammy to runtime config for VMs on Jammy stemcells
- Add awslogs-jammy release to be referenced by pipeline for dev/stage
None
> Add awslogs jammy to runtime config

- ci/pipeline.yml
Related to https://github.com/cloud-gov/product/issues/2397
Add awslogs-jammy BOSH release as trigger for prod BOSH deployment. However, the awslogs-jammy BOSH release will only be run on VMs using Ubuntu Jammy stemcells per the runtime config.
None
> add awslogs-jammy release as trigger for prod

- bosh-create-env.sh
- ci/pipeline.yml
- As part of master bosh `create-env` there is a `creds.yml` that is not backed up and does/can contain some secrets we could need in the event of a restore.  This adds a task to backup that file to the S3 bucket for BOSH
Having all the secrets is a good thing especially with encryption.  I notable one in this file is nats encryption password
> backup master bosh creds.yml to s3

- bosh-create-env.yml
- ci/pipeline.yml
- Add in more resource definitions for bosh-creds resource to track `create-env` `creds.yml` in S3 so we don't loose new secrets
Keeping secrets is a good thing - even better when we need them for recovery
> updating pipeline and create-env.yml for bosh-creds

- cloud-config/main.yml
- Add in reserved IP into cloud-config for services network for internal domains LB so BOSH doesn't try to use that IP
BOSH is only aware of IPs in use either by what is defined in the reserve range or IPs it uses to deploy VMs. So by having IPs in use in either the static or dynamic range defined to a BOSH network, BOSH can try and use that IP, run into an IP conflict, and not finish a deployment due to the error and cause a blockage until the issue is resolved.
n/a
> adding in logic to reserve ip for internal domain lb

- operations/cpi.yml
- Enable CPI IaaS resize for storage volumes
This allows native AWS EBS expansion rather then attach new and `rsync` data
N/A
> Adding resize for aws disk

- operations/s3-blobstore.yml
- Since we are specifying s3 blobstore. We don't need dav blobstore at all
-
-
Actually reduces stuff in BOSH VM
> remove local blobstore job

- cloud-config/main.yml
- Updated the disk size from 7 to 12 TB to give logsearch more room
-
-
None, just changing disk size
> Updated logsearch to move from 7 to 12 TB to give more room in Prod

- operations/external-db-protobosh.yml
- operations/s3-blobstore-protobosh.yml
- Removing extra jobs which talk to a local db
-
-
None, forces the RDS db to be used instead of a local postgres instance
> Removing extra jobs which talk to a local db

- operations/external-db-protobosh.yml
- create-env for protobosh requires a full url path, adding this for toolbelt for new westa-hub
-
-
Might consider removing toolbelt in the future, there are other ways of getting psql client installed
> Adding url for toolbelt for westa-hub protobosh

- operations/ca.yml
- Updated the ca.yml to use default_ca.ca
-
-
None, we are using a cert which ultimately is better security
> updated ca cert to use the ca

- operations/cpi-protobosh.yml
- Adding a separate cpi for protobosh to use distinct instance profile
-
-
Allows us to distinguish between what tooling is using as a default profile and what protobosh is using
> Adding a separate cpi for protobosh to use distinct instance profile

- variables/tooling.yml
- The current configuration doesn't allow the results of the cron job to be pushed to prometheus
-
-
This should alert us going forward of instances in tooling provisioned outside of the bosh director
> fix for cron.yml in tooling for missing gateway

- cloud-config/protobosh.yml
- operations/external-db-bosh-rds.yml
- operations/use-c5-large.yml
- variables/westa-hub-tooling.yml
- Remove unused bbr jobs that would consume resources but not be used since we leverage rds snapshots
- Bumped default instance type for protobosh
- Use the more restricted instance profile created specifically for the toolingbosh
- Change to cloud config needed to deploy tooling bosh
Removes potential attack surface of unused bbr jobs and tightens instance profile in use
> Changes needed for tooling bosh

- cloud-config/cf.yml
- cloud-config/protobosh.yml
- Add another vm_extension for the uaa load balancer
- Background: The uaa load balancer is being removed from the cf-router-network-properties vm_extension into its own so the traffic can be split via cg-provision's outputs.tf in the main stack
-
None
> Add vm_extension for uaa load balancer

- releases/releases.yml
- remove opensearch because it has its own pipeline to make releases
-
-
none
> removing opensearch as it has a pipeline to make a new release

- cloud-config/main.yml
- cloud-config/tooling.yml
Related to https://github.com/cloud-gov/product/issues/2376
- move types to use gp3 instead of gp2. gp3 is now the default for disk types on AWS, but some of these disk types precede that change, so they have to be upgraded to gp3
None, just moving from gp2 to gp3 volumes to optimize cost and performance
> update disk types to gp3

- cloud-config/master.yml
Related to https://github.com/cloud-gov/product/issues/2376
- Update the cloud-config template uploaded to the master bosh for deploying the tooling bosh to use gp3 disk
-
-
None
> Update master bosh cc for gp3 for tooling

- ci/pipeline.yml
- Put lock and unlock steps on a single job for now, just to test that they work.
- See demo in https://github.com/cloud-gov/concourse-locks
Uses CI bot to write back to GitHub.
> Pilot using lock step to control job parallelism across pipelines

- ci/pipeline.yml
- Updates to use hardened container images
Uses hardened container images, and uses our slack notification resource rather than the cloudfoundry-community resource
> update resources to use hardened images

- ci/pipeline.yml
- releases/releases.yml
- Replaced cloudfroundry-community with cloud-gov for the cron-boshrelease
- 
-
None
> updating cron boshrelease to use forked internal repo

- cloud-config/base.yml
- Add m5.large.concourse.web instance type to the cloud config so it can be used on Tooling for concourse
- Web nodes have higher than desired swap usage
- Part II is to change cg-deploy-concourse
None
> Adding new instance type for concourse web

- ci/update-runtime-config.sh
- operations/cpi.yml
- runtime-config/runtime.yml
- variables/master.yml
- Add a new tag called `cg_environment` with the corresponding environment on each BOSH director and BOSH deployment
- This will allow us to add that tag to AWS Cost explorer so we can better group EC2 resources where deployments don't have environment names aka logsearch
- This also adds the tags run runtime configs for tooling/dev/stage/prod as well
Local manifest tags take preference over runtime tags
By tagging EC2 resources deployed by BOSH helps us better audit our environments
> Adding environment tags to BOSH deployments

- bosh-create-env.sh
-  Moving the masterbosh create-env script to use the precomplied releases coming from bosh deployment to reduce deployment time
None
> Moving to use pre-complied releases from bosh-deployment to reduce masterbosh deployment time

- cloud-config/development.yml
- logsearch dev nodes hit 90% disk space in use - bumping disk
none
> bumping logsearch dev data disk

- releases/pipeline.yml.erb
- Updates the bosh release pipeline to use hardened image
Pipeline should be using hardened images
> update release pipeline to use hardened images

- cloud-config/base.yml
- Need larger instance types for bigger cells
- https://github.com/cloud-gov/product/issues/3024
-
None.  Just adds more instance types to cloud config
> Add larger r6i to cc

- cloud-config/tooling.yml
- Nessus manager is using a burstable T class and running into CPU and memory constraints to moving to a larger/stable instance class 
n/a
> making large instance type for nessus mgr

- cloud-config/tooling.yml
- Deployment was torn down so no longer need cloud config network and vm extension blocks for it
- Closes https://github.com/cloud-gov/private/issues/1369
-
None.  Removes references to deprecated deployment
> Remove references to pages concourse

- releases/pipeline.yml.erb
- releases/releases.yml
Sets the fips endpoint for the bosh blobstore
The fips endpoint is required for compliance
> Fips endpoint

- releases/pipeline.yml.erb
- uses the fips endpoint for s3 concourse resources
Use of the FIPS endpoint is required for compliance
> use fips endpoint for pipeline resources

- operations/s3-blobstore.yml
- variables/development.yml
- variables/production.yml
- variables/staging.yml
- variables/tooling.yml
Enables the configuration of blobstore server side encryption through variables. This will enable the test and rollout of KMS encryption for the bosh blobstores.
KMS encryption is required for FIPS 140 compliance.
> configuration of blobstore server side encryption with variables

- operations/cpi.yml
- Require IMDSv2 for all vms created by each bosh director
- Tested against CF staging and passes smoke and acceptance tests.
- A similar configuration already exists on diego cells and both flavors concourse workers
- Part of https://github.com/cloud-gov/private/issues/1911
Forces the use of a token to access metadata information
> Require IMDSv2

- bosh-create-env.sh
- operations/masterbosh-metadatav2.yml
- Require IMDSv2 for the masterbosh director
- The rest of the bosh directors were solved with: https://github.com/cloud-gov/deploy-bosh/pull/625
- Part of https://github.com/cloud-gov/private/issues/1911
Forces the use of a token to access metadata information
> Adding IMDSv2 to masterbosh

- cloud-config/base.yml
- Require IMDSv2 for all vms created by each bosh director, this removes the vm_extension in the cloud_config which was used to enable IMDSv2 only for a small subset of vms since this is configured globally.
- Part of https://github.com/cloud-gov/private/issues/1911
Forces the use of a token to access metadata information
> Remove meta-data-v2 extension

- ci/pipeline.yml
- Modify pipeline to run a single concourse task at a time to avoid deployment conflicts
- Experiment to see if this helps deconflict deploys
-
Only forces tasks to run in single file, no change in security stance.
> Run pipeline tasks one at a time

- operations/s3-blobstore-protobosh.yml
- operations/s3-blobstore.yml
- Matching https://github.com/cloudfoundry/bosh-deployment/blob/master/aws/s3-blobstore-instance-profile.yml
- Less Certs to worry about that we do not use
-
None, reduces maintenance and unused resources
> Removed unneeded blobstore certs since we use S3

- ci/pipeline.yml
now that node-exporter-release is available as an official release, we should use it
- update to official node-exporter-release
This improves security by allowing us to stay up-to-date on node-exporter while avoiding the issues with the cf-community org
> chore: update to official node-exporter-release

- releases/releases.yml
- Removes the wazuh agent configuration in favor of a pipeline in the agent bosh release repo.
- No impact.
> build wazuh agent in release repo

- cloud-config/root-disk.yml
- Adds an opsfile which will allow root disk size overrides to be added to the BOSH Cloud Config
- Part of https://github.com/cloud-gov/private/issues/2250
-
None, this adds another ops file that will make available overrides for the default 5GB root disk size
> Adding root-disk.yml ops file

- cloud-config/main.yml
- logsearch no longer uses static ips
-
-
None, makes our life easier
> no more static ips

- cloud-config/main.yml
- Adds z2 availability zone to the `services` network to the cloud-config for dev/stage/prod directors
- Will allow the opensearch and logsearch deployments to be multi-az
- Part of https://github.com/cloud-gov/private/issues/2469
Same security group as z1
> Adding services_subnet_cidr_az2

- cloud-config/tooling.yml
- Rollback concourse az2, needs more vpc peering work and need to unblock stemcell rollout
- Part of https://github.com/cloud-gov/private/issues/2469
-
None, rolls back to previous configuration
> Rollback concourse az2

- cloud-config/tooling.yml
- Adding Concourse az2 to staging and production
- Part of https://github.com/cloud-gov/terraform-provision/pull/1975
Just adds another az for vms
> Add Concourse az2 back

- cloud-config/tooling.yml
- Change prometheus-large-disk to 1.2TB gp3
- Current config uses io1 disk with 14k iops
- Verified via grafana that the iops used fall in the range of gp3 iops at 3k
- Also scaling disk down to 2x-ish what is currently used
- Part of https://github.com/cloud-gov/private/issues/2594
None, changes a disk pool size and type for 1 vm
> Change prometheus-large-disk to 1.2TB gp3

- ci/pipeline.yml
- Remove trigger for terraform changes which causes some of the churn in Slack
- Change is already applied to the pipeline since it is not self setting
- https://github.com/cloud-gov/product/issues/2836
None, switches a trigger from automatic to manual
> Remove trigger for terraform changes

- ci/pipeline.yml
- operations/tooling-bosh-awslogs.yml
- runtime-config/runtime.yml
- Removes `awslogs` from the runtime configuration for all BOSH directors
- Adds the job back to Tooling BOSH for now.  There is a cron job that relies on the AWS CLI being installed, and you guessed it, relies on the package included by this release.  I'll come up with a cut down bosh release later on for the AWS CLI but want to start rolling with this in the meantime.
- Part of https://github.com/cloud-gov/private/issues/2623
Removes duplicate platform logs that are also being sent to cloudwatch.
> Remove awslogs from BOSH runtime

- runtime-config/runtime.yml
- Add auth.log and dpkg.log to syslog since awslogs will no longer be doing this
- audit.log is omitted because those logs are already included in syslog.  Adding it is ignored since the messages already go to syslog.
- syslog is omitted because it is already included, adding it explicitly causes a snowball effect of the logging of syslog being recorded by syslog being recorded by syslog... until the syslog fills the disk and the vm falls over.  Sorry Jason. These logs already are in logs platform anyway.  
- Part of https://github.com/cloud-gov/private/issues/2623
Adds logging of required files to syslog that awslogs used to do
> Add auth.log and dpkg.log to syslog via runtime config
