- credentials.example.yml
- pipeline.yml
Ensure that all our directors have the common releases on them that we need for 18F/cg-atlas#57
> Upload common resources to each bosh

- pipeline.yml
> add clamav and riemannc to the common releases

- bosh-deployment.yml
- bosh-init-deployment.yml
Pairing with @jmcarp on updating properties. Part of 18F/cg-product#42
cc: @linuxbozo
> Update encrypted properties

- pipeline.yml
> Upload snort release.

- pipeline.yml
h/t @LinuxBozo 
Also snuck in moar yaml references.
> Add snort to tooling releases.

- credentials.example.yml
- pipeline.yml
* Add `common-releases-master` job
* Add dummy `put` on common releases jobs
* Deploy tooling and staging bosh after common release updates
[Resolves https://github.com/18F/cg-atlas/issues/117]
cc @LinuxBozo
> Add hardening releases to master and tooling bosh.

- credentials.example.yml
- pipeline.yml
* Master bosh has no SSL cert
* Allow separate AWS credentials for semver resources
@LinuxBozo
> Delete master-bosh cert.

- credentials.example.yml
- pipeline.yml
> Include reimann in common releases jobs

- bosh-deployment.yml
- pipeline.yml
* Add bosh log forwarder to common releases
* Forward bosh logs to elastic
> Forward logs to elastic.

- bosh-deployment.yml
> Updates to help support using BOSH UAA for more ops authentication

- bosh-deployment.yml
- pipeline.yml
This reverts commit b9c95a020423327429f7ba427b343f91ec2992ba.
> Revert "Forward logs to elastic."

- bootstrap.sh
- bosh-deployment.yml
- bosh-init-deployment.yml
- credentials.example.yml
- generate.sh
- pipeline.yml
- tooling-uaa.yml
* Switch from spiff to spruce
* Check in non-sensitive UAA configuration
* Clean up pipeline cruft
@LinuxBozo
> Check in non-sensitive configuration.

- bosh-deployment.yml
- bosh-init-deployment.yml
https://github.com/18F/cg-product/issues/309
> replaced x.pool with continental zones and a third server to ntp config

- cronjobs/unknown-vms.sh
This is for https://github.com/18F/cg-product/issues/458
> Emit metrics for known and unknown vms

- bosh-deployment.yml
> Flush ARP on recreate.

- runtime-config.yml
> Delete extra parenthesis in runtime config.

- credentials.example.yml
- pipeline.yml
- runtime-config.yml
> Add missing addon releases.

- bosh-init-deployment.yml
> Upgrade master bosh releases and stemcell.

- pipeline.yml
- update-runtime-config.sh
- update-runtime-config.yml
> Get release versions from tarballs.

- generate.sh
- tooling-uaa.yml
Part of https://github.com/18F/cg-atlas/issues/175.
> Provision monitoring clients.

- credentials.example.yml
- pipeline.yml
> Parameterize pipeline task resource.

- runtime-config.yml
> Remove cron for real

- bosh-deployment.yml
See https://github.com/cloudfoundry/bosh/issues/1486.
> Enable post-deploy scripts.

- credentials.example.yml
- pipeline.yml
- tooling-uaa.yml
Use client creds for tooling bosh.
> Bosh client auth

- tooling-uaa.yml
So we can audit tokens from opslogin.
> Add token audit uaa client.

- bosh-deployment.yml
- tooling-uaa.yml
Check in prometheus clients. Will need to update secrets before this rolls out.
> Add prometheus bosh exporter and grafana clients.

- generate-bosh-certs.sh
- pipeline.yml
Depends on https://github.com/18F/cg-provision/pull/197.
> Add development bosh.

- pipeline.yml
- tooling-uaa.yml
> Customize opslogin uaa.

- bosh-deployment.yml
- bosh-init-deployment.yml
- generate.sh
- pipeline.yml
- runtime-config.yml
Goes with https://github.com/18F/cg-provision/pull/206.
> [WIP] Use instance profiles instead of IAM users.

- bosh-deployment.yml
Hopefully this is the last one I missed.
> Add missing instance profile config.

- bosh-deployment.yml
Going to have to submit a bunch of patches like this one @LinuxBozo
> Specify compilation instance profile.

- bosh-deployment.yml
> Use upstream bosh compilation profile.

- pipeline.yml
- runtime-config-staging.yml
- update-runtime-config-staging.yml
- update-runtime-config.sh
Add node exporter to runtime config, for staging only as @cnelson suggested.
cc @LinuxBozo
> Add prometheus node exporter to bosh addons.

- pipeline.yml
> Various updates to the pipeline

- bosh-deployment.yml
- pipeline.yml
* UAA SSL listens on 8444
* Nginx listens on 8443 and proxies to 8444
wdyt @LinuxBozo ?
> Add secureproxy to uaa.

- pipeline.yml
> Upload secureproxy release.

- cloud-config.yml
- cloud-config/cloud-config-base.yml
- cloud-config/cloud-config-main.yml
- cloud-config/cloud-config-tooling.yml
- pipeline.yml
- update-cloud-config.sh
- update-cloud-config.yml
- update-runtime-config.sh
We'll probably want to split up files by bosh (tooling / prod / staging / dev) and component (concourse / monitoring / cf) as in https://github.com/alphagov/paas-cf/tree/master/manifests/cf-manifest/cloud-config, but this is a start.
cc @cnelson @LinuxBozo
> [WIP] Add cloud config to tooling bosh.

- pipeline.yml
Forgot to check this in yesterday 😓
> Fix tooling cert.

- cloud-config/cloud-config-tooling.yml
Goes with https://github.com/18F/cg-provision/pull/229.
> Set reserved address ranges from terraform.

- cloud-config/cloud-config-main.yml
- cloud-config/cloud-config-tooling.yml
Goes with https://github.com/18F/cg-deploy-concourse/pull/51.
> Add tenant concourse settings to cloud config.

- cloud-config/cloud-config-main.yml
Pairing with @rogeruiz @pburkholder @wjwoodson
> Add shibboleth cloud config.

- cloud-config/cloud-config-main.yml
This was lost (by me) during migration to cloud config.
> Restore IDP ephemeral disk.

- bosh-create-env.sh
- bosh-create-env.yml
- bosh-deployment.yml
- bosh-development.yml
- bosh-production.yml
- bosh-staging.yml
- bosh-tooling-uaa.yml
- bosh-tooling.yml
- cloud-config/cloud-config-bosh.yml
- cloud-config/cloud-config-main.yml
- cloud-config/cloud-config-master.yml
- cloud-config/cloud-config-tooling.yml
- pipeline.yml
- update-cloud-config-tooling.sh
- update-cloud-config-tooling.yml
Deploy tooling, development, staging, and production bosh with cloud-config.
Depends on https://github.com/18F/cg-provision/pull/251.
> Deploy bosh using cloud config.

- bosh-deployment.yml
> Security groups must be an array.

- bosh-deployment.yml
- bosh-tooling.yml
Bosh really needs to make use of links 😓
> Restore custom tooling domain.

- bosh-create-env-deployment.yml
* Secrets from terraform
* Use bosh2 styles, modulo cloud config
> [WIP] Merge master bosh properties from terraform.

- bosh-create-env-deployment.yml
@jmcarp I think this will fix the masterbosh deploy
> cpi needs registry properties

- cloud-config/cloud-config-tooling.yml
Importing the vm_type, vm_extension, disk_type, and network.
> Migrate Nessus Manager To Cloud Config

- cloud-config/cloud-config-main.yml
Goes with https://github.com/18F/cg-deploy-diego/pull/30 and https://github.com/18F/cg-provision/pull/263.
> Create platform cell instance profile extension.

- releases/generate.rb
- releases/generate.sh
- releases/pipeline.yml.erb
- releases/releases.yml
After concourse tagged workers with instance profiles are done, there should be no secrets here, unless we want to consider bucket names secret. To update the bosh release pipeline, an operator would update `releases/releases.yml` as needed and run `releases/generate.sh`.
> [WIP] Build release pipeline from template.

- releases/releases.yml
Adding releases as I find them while removing amazon creds
> Add kubernetes to common release pipeline

- cloud-config/cloud-config-main.yml
Importing the instance_type, disk_type, and networks.
> Migrate Kubernetes To Cloud Config

- cloud-config/cloud-config-base.yml
- cloud-config/cloud-config-main.yml
> Add generic errand machines and profile.

- cloud-config/cloud-config-main.yml
* Add kubernetes security group
* Move kubernetes load balancer to separate extension for cleaner names
> Add kubernetes security group.

- bosh-lint.yml
- pipeline.yml
Add linter check before dev, stage, prod bosh deployments
> Add linter check

- releases/releases.yml
> Fix newrelic upstream link.

- bosh-create-env-deployment.yml
- pipeline.yml
This branch deployed successfully here https://ci.fr.cloud.gov/teams/main/pipelines/deploy-bosh/jobs/deploy-master-bosh/builds/124
> use instance profiles for bosh create-env

- cloud-config/cloud-config-tooling.yml
Now that we actually have a retention policy on influx, it's using way less resources.  I think we can scale it down to this and save  ~ $8400/year.
> scale down influx

- cloud-config/cloud-config-development.yml
- pipeline.yml
- update-cloud-config-tooling.sh
- update-cloud-config.sh
> Dev cloud config

- cloud-config/cloud-config-tooling.yml
Ref: https://gsa-tts.slack.com/archives/C0A1Z7L2U/p1501271523791247
> our SSP says indefinite retention for nessus

- cloud-config/cloud-config-tooling.yml
Goes with https://github.com/18F/cg-deploy-prometheus/pull/23.
> Bump prometheus instance type and disk.

- cloud-config/cloud-config-development.yml
- cloud-config/cloud-config-main.yml
- pipeline.yml
- runtime-config.yml
- update-runtime-config-staging.yml
- update-runtime-config.sh
- update-runtime-config.yml
Goes with https://github.com/18F/cg-provision/pull/297.
> [WIP] Add platform logsearch load balancers.

- cronjobs/unknown-vms.sh
Until bosh team decides if this is WONTFIX or not
> make cron script work with recent bosh

- cloud-config/cloud-config-tooling.yml
until bosh explains how to change FS types when using cloud-config
> Double the inodes

- bosh-deployment.yml
- bosh-development.yml
- bosh-production.yml
- bosh-staging.yml
- bosh-tooling.yml
- cronjobs/unknown-vms.sh
This just contains the command that's needed to hit the PushGateway.
Still needs to be refactored to use the correct path and metric.
Handing this work over to @wjwoodson
> Port Unknown VMs script from Riemann to Prometheus

- bosh-deployment.yml
Instead of getting ips from secrets. Depends on https://github.com/18F/cg-provision/pull/307.
> Get nat gateway ips from terraform.

- pipeline.yml
Cut down release uploading boilerplate.
> Simplify release uploads.

- bosh-tooling.yml
> Restore uaa customized release to tooling.

- bosh-tooling.yml
> Drop unused spruce appends.

- cronjobs/unknown-vms.sh
So that we don't clobber the last metric each time we push a new one.
Pairing with @wjwoodson
> Send unknown vms metrics in single request.

- bosh-create-env-deployment.yml
- bosh-deployment.yml
- generate.sh
- pipeline.yml
Part of the https://github.com/18F/cg-secret-rotation experiment.
cc @wjwoodson
> Merge secrets from common secrets hash.

- cloud-config/cloud-config-main.yml
- pipeline.yml
- runtime-config.yml
- update-runtime-config.yml
* Add nfs volume driver to diego via runtime config
* Add cloud config for test nfs server
> [WIP] Configure nfs volume services.

- bosh-deployment.yml
- bosh-tooling.yml
This depends on https://github.com/18F/cg-provision/pull/318 for tooling deployment
> grab bosh_static_ip from terraform

- pipeline.yml
- runtime-config/base.yml
- runtime-config/runtime-config-volume-driver.yml
- update-cloud-config-tooling.sh
- update-cloud-config.sh
- update-runtime-config.sh
Haven't verified yet--needs review or pairing before merge.
> [WIP] Handle differences in runtime config between environments.

- bosh-create-env-deployment.yml
- bosh-deployment.yml
- generate-bosh-certs.sh
- generate-master-bosh-certs.sh
I haven't tested this yet! Let's verify on dev bosh and fix whatever issues come up before merging. Certs will need to be added to cg-secret-rotation too.
@sharms @wjwoodson
> [WIP] Add certs for nats mtls.

- bosh-deployment.yml
> Enable uniqueness restriction on refresh tokens.

- cloud-config/cloud-config-base.yml
- cloud-config/cloud-config-development.yml
- cloud-config/cloud-config-main.yml
- cloud-config/cloud-config-staging.yml
- cloud-config/cloud-config-tooling.yml
> Encrypt all ephemeral volumes with default size.

- bosh-deployment.yml
> Drop extraneous whitespace in cron config.

- bosh-deployment.yml
> Get rid of errant linebreak

- bosh-create-env-deployment.yml
- bosh-create-env.sh
- bosh-create-env.yml
- bosh-deployment.yml
- bosh-tooling-uaa.yml
- pipeline.yml
Interpolate vars from file generated at runtime from secrets files instead of all the per-deployment silliness in https://github.com/18F/cg-deploy-bosh/pull/173
> [WIP] Prep pipeline and deployments for shared secret process

- bosh-create-env-deployment.yml
Get access to master-bosh vm for troubleshooting and contingency plan.
Restore master-bosh naming.
> Set password for master-bosh

- cloud-config/cloud-config-tooling.yml
To prevent prometheus from thrashing in and out of rushed mode.
> Bump prometheus instance type.

- cloud-config/cloud-config-tooling.yml
> Restore monitoring networks.

- bosh-deployment.yml
- bosh-development.yml
- bosh-production.yml
- bosh-staging.yml
- bosh-tooling-uaa.yml
- bosh-tooling.yml
- generate-bosh-certs.sh
This would split UAA into it's own VM (which then can be scaled separately)
Tested in dev
> Make it so UAA for bosh can be HA

- bosh-create-env-deployment.yml
- bosh-deployment.yml
Option added in https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/releases/tag/v67.
> Encrypt all EBS volumes.

- ci/update-cloud-config-tooling.yml
- ci/update-cloud-config.yml
- ci/update-runtime-config-tooling.yml
- ci/update-runtime-config.yml
> Update script paths in task yaml files.

- cloud-config/cloud-config-base.yml
> Fix fake az3 for cf-deployment.

- cloud-config/cloud-config-base.yml
- cloud-config/cloud-config-main.yml
* Revert z3 to avoid overlapping subnets
* Drop bosh static ip from z2 reserved
> Drop fake third availability zone.

- cloud-config/cf.yml
> Add cf blobstore instance profile to vm extensions.

- ci/pipeline.yml
https://github.com/18F/cg-deploy-bosh/pull/219/
> point to new cloud config main

- ci/pipeline.yml
- cloud-config/cf.yml
- cloud-config/production.yml
> Combine elb vm extensions to avoid clobbering.

- cloud-config/tooling.yml
> Bump nessus manager disk from 120G to 200G

- cloud-config/main.yml
Part of elasticache broker feature.
> Add elasticache broker cloud config.

- cloud-config/tooling.yml
- releases/releases.yml
> Pdns config

- cloud-config/tooling.yml
> Add vm type for powerdns.

- cloud-config/tooling.yml
https://github.com/18F/cg-provision/pull/346
> Switch to granular dns security groups.

- cloud-config/tooling.yml
> Fix dns security groups.

- cloud-config/main.yml
- cloud-config/staging.yml
> Drop cloud config related to tenant concourse.

- bosh-deployment.yml
Force details for session cookies. Mitigates SAR results.
> Update details of UAA session cookies

- cloud-config/cf.yml
- cloud-config/main.yml
- cloud-config/master.yml
- cloud-config/tooling.yml
Goes with https://github.com/18F/cg-provision/pull/380.
> [WIP] Balance instances behind both ELBs and ALBs.

- cloud-config/tooling.yml
> Update m3 instance types to m4.

- ci/pipeline.yml
No need for github access tokens
> Switch to bosh.io release.

- releases/releases.yml
> Build nfs-volume release.

- ci/pipeline.yml
- operations/cron.yml
It might make more sense to move this cron job to concourse, but for now, let's make it work again on the bosh directors.
> Restore cron

- operations/cron.yml
- variables/development.yml
- variables/production.yml
- variables/staging.yml
> Restore cron gateway host.

- releases/releases.yml
master now uses our own fork of the code with all the fixes
> update oauth2_proxy branch

- bosh-tooling.yml
- cloud-config/master.yml
> Drop tooling bosh uaa instances from ops uaa load balancer.

- ci/pipeline.yml
- operations/toolingbosh-tld.yaml
Doing with @sharms and @jmcarp
> change tooling bosh tld to be proper

- operations/cron.yml
* Replace existing metrics with PUT
* Drop redundant last check metric; now provided by push gateway
> Clean up unknown vms metrics.

- operations/cron.yml
> Drop stray character from cron config.

- bosh-create-env.sh
- ci/pipeline.yml
I'll rename the secrets files in s3 after merge.
> Use consistent names for secrets files.

- ci/pipeline.yml
- ci/update-cloud-config-tooling.sh
- ci/update-cloud-config.sh
- cloud-config/base.yml
- cloud-config/bosh.yml
- cloud-config/cf.yml
- cloud-config/development.yml
- cloud-config/main.yml
- cloud-config/master.yml
- cloud-config/staging.yml
- cloud-config/tooling.yml
Goes with https://github.com/18F/cg-provision/pull/464.
> [WIP] Manage cloud config with opsfiles instead of spruce.

- ci/update-cloud-config-tooling.sh
- cloud-config/master.yml
Fix invalid yaml and shell typos from initial patch for cloud config to opsfile migration.
> Fix typos around cloud config ops file migration.

- cloud-config/development.yml
- cloud-config/staging.yml
> Use smaller instances for development diego cells.

- ci/update-cloud-config.sh
- cloud-config/isolation-segment.yml
Specific isolation segments can be added in separate patches.
> Add cloud config for isolation segments.

- operations/dns-aliases.yml
Goes with https://github.com/18F/cg-deploy-prometheus/pull/98
> Add DNS aliases for prometheus alertmanager.

- cloud-config/development.yml
This didn't get updated like staging/production for more clamav data
> Larger disks for ELK platform on dev

- operations/source-release-credhub.yml
:eyes: https://cloudfoundry.slack.com/archives/C3EN0BFC0/p1539280330000100
> Update to the version that supports Arrays as JSON

- operations/source-release-credhub.yml
Should fix issue with DB cert.
> Credhub release 2.1.1

- releases/releases.yml
@sharms it's okay to merge this now :trollface:
> Add the trusty suffix

- bosh-create-env.sh
- operations/remove-postgres.yml
Fixes master bosh failing because of no pg job.
> Add ops for masterbosh db removal

- ci/pipeline-development.yml
- ci/pipeline.yml
- ci/update-runtime-config.yml
- operations/cloud-config.yml
- operations/cron.yml
- runtime-config/runtime.yml
Updates stemcell to xenial and renames stemcell resource so Concourse does not get confused by xenial's lower version numbers
> Update stemcell to xenial

- ci/pipeline.yml
@hillaryj @RonWilliams We need to do this across all our pipelines, sooner than later, to head off any compatibility issues with future releases of concourse.
> Refactor aggregate to in_parallel

- cloud-config/main.yml
More power for the unruly minions.
> Update ec2 intances for kubernetes

- cloud-config/staging.yml
> reseting back to older change.

- releases/releases.yml
follow-up to 18F/cg-awslogs-boshrelease#31
> update branch to master since upgrade-to-xenial has been merged

- cloud-config/staging.yml
> resize logsearch disk

- .gitignore
- ci/pipeline.yml
This pulls the current pipeline config into git.
Not sure how we got out of sync, but this fixes it
> Sync pipeline with reality

- bosh-create-env.sh
- bosh-create-env.yml
this is the branch masterbosh currently deploys from, and has been doing for an unknown length of time¯\\\_(ツ\)_/¯
> Add ch to masterbosh

- ci/pipeline.yml
these are duplicates, and that is now a sytax error
> remove repeated resources

- bosh-create-env.sh
this also runs masterbosh on the credhub source release, hopefully fixing credhub.
> run masterbosh from credhub source, too

- operations/s3-blobstore.yml
This reverts commit d3cff1465a568dcb0556ab1815bf8a3d5d023ccc.
> Revert "set s3 config on bosh agents"

- operations/dns-aliases.yml
- operations/dns.yml
this should reduce the logs from bosh-dns a bit.
> less logs from bosh-dns

- cloud-config/tooling.yml
Maps Doomsday to the internal tooling ELB.
> added vm extensions for doomsday.

- ci/update-runtime-config.sh
- ci/update-runtime-config.yml
- fix broken builds
This shouldn't change any configurations as they are already in Credhub.
Finishes Credhub integration with customer-facing bosh director deployments.
> removed vars file references.

- runtime-config/runtime.yml
- fix bad deployments with missing variables.
Fix credential reference.
> fixed missing variables for runtime configs.

- runtime-config/runtime.yml
> fixed credential type as bosh sees it.

- runtime-config/runtime.yml
> set nessus to be a root path.

- ci/pipeline.yml
- remove vars file.
Closes https://github.com/18F/cg-product/issues/1212
Ensures toolingbosh reads from Credhub.
> removed vars file from tooling bosh.

- bosh-create-env.sh
- oops. removed duplicate releases.
None.
> fixing the releases.

- ci/pipeline.yml
- forgot to update the pipeline configs.
None.
> fixed source references.

- operations/ntp.yml
- bad key, just fixing it.
None.
> fix ntp key.

- operations/external-db.yml
- just fixing a key location.
None.
> fixed bad key location.

- bosh-create-env.sh
- operations/add-postgres-9.yml
- Masterbosh should use psql 10.
Some, just whatever fixes come with psql 10.
> upgrade psql to v10.

- bosh-create-env.sh
- ci/pipeline.yml
- operations/add-cloud-gov-root-certificate.yml
- Add cloud.gov root certificate for easier trust.
None, this is a public certificate, this just adds more trust.
> added cloud.gov root certificate to all machines.

- cloud-config/base.yml
- unblocks https://github.com/18F/cg-deploy-opslogin/pull/16 for merging.
None.
> add dedicated type for opsuaa.

- cloud-config/base.yml
- operations/update.yml
- moved generation
- added bosh-specific alias.
None.
> changed alias and moved generation forward.

- cloud-config/base.yml
- unblocks https://github.com/18F/cg-deploy-nessus-manager/pull/27
- adds dedicated type.
None.
> added dedicated nessus type.

- cloud-config/base.yml
- make things a bit bigger.
None.
> added dedicated type with ephemeral disk.

- ci/pipeline.yml
- Fix typo in ops file name
None
Signed-off-by: Chris McGowan (christopher.r.mcgowan@gsa.gov)
> fix typo in ops add for pipeline

- ci/pipeline.yml
- add AIDE as a common boshrelease to be uploaded to all environments
None
> add aide to common releases

- ci/update-runtime-config.yml
- update-runtime-config is broken because it's not getting the AIDE release. Fix it by passing it the release
None
> update update-runtime-config to add aide

- cloud-config/tooling.yml
Adds load balancer extensions for the credhub staging and prod.
None
> add credhub lb extensions

- cloud-config/development.yml
- Removed VM extensions for DEV only
None
> Removed k8s stuff for bosh dev

- cloud-config/development.yml
- cloud-config/main.yml
- First I removed an extra `-` for the kubernetes-lb insertion because this would making things harder to remove
- Fixed the paths to be working
None
> Fixed Dev's removals and one in main.yml

- cloud-config/development.yml
- cloud-config/main.yml
- cloud-config/staging.yml
- Removes k8s VM extension + vm types from main.yml
- Removes k8s removes in dev/staging
None
> K8s teardown production

- cloud-config/staging.yml
- Removed Staging k8s stuff
None
> Removed staging k8s stuff

- cloud-config/staging.yml
- more staging k8s removal
None
> Removed more staging k8s

- releases/releases.yml
> drop unused releases

- cloud-config/tooling.yml
- more space for production prometheus. Required for cloud-gov/cg-deploy-prometheus#159
None
> more space for production prometheus

- ci/update-runtime-config.sh
- operations/add-bosh-san.yml
- added a new file with SAN details in order to upgrade bosh dns. 
none
> adding in san stuff 

- ci/pipeline.yml
- releases/releases.yml
- runtime-config/runtime.yml
- Add in build pipeline support for awslogs-bionic to support bionic stemcells
n/a
> setting new build pipeline for bionic

- ci/update-runtime-config.yml
- Add line for correct runtime release variable
n/a
> missed one

- releases/releases.yml
- update admin-ui release to stop using jmcarp form
improves our visibility and control of changes
> stop using repo from departed team members

- operations/cloud-config.yml
- Moving operations cloud-config to now default to bionic
let's patch CVEs and get off xenial 😎
> moving bosh directors to the future

- ci/pipeline.yml
- Remove use of xenial stemcell and replace with bionic stemcell for all directors
- Move stemcell to bionic and lessen CVEs from using xenial
> change pipeline to deploy bionic for all bosh directors

- cloud-config/cf.yml
- Fix error listing wrong size for vm ext to increase to correct 5 GB amount
n/a
> fix vm extension size for 5 gb disk

- cloud-config/tooling.yml
- Added vm_ext for 5gb ephemeral disk in tooling env 
n/a
> adding 5gb ephemeral disk to vm extensions for tooling

- cloud-config/tooling.yml
- 10 gb ephemeral disk to tooling cloud-config
n/a
> adding 10gb ephemeral disk to tooling

- bosh-create-env.sh
- ci/pipeline.yml
- operations/add-nessus-agent.yml
- variables/terraform-master.yml
- Add nessus-agent to master bosh
Allows our standard compliance scan tool to scan master bosh
> Nessus-agent

- ci/pipeline.yml
- operations/add-nessus-agent.yml
- Update CI logic for correct resource path
To install nessus-agent on master bosh
> Nessus2 - path fix

- bosh-create-env.yml
- Add input to create-env file for nessus-agent
load nessus-agent on master bosh
> add input to create-env.yml

- operations/add-nessus-agent.yml
- update path in ops file
This loads nessus-agent onto master bosh
> moving path for nessus-agent ops file

- operations/add-nessus-agent.yml
- Path might be wrong so trying to fix it
-
-
None
> improve path for nessus agent

- bosh-create-env.sh
- nessus agent isnt working but we gotta roll out new patches
-
-
None
> Temp remove agent

- bosh-create-env.sh
- operations/add-nessus-agent.yml
- Add nessus release tracking
- Add logic to create-env script to get latest release version and update ops file on the fly
Having nessus on master bosh allows better reporting
> Add nessus agent to master bosh

- bosh-create-env.sh
- Add nessus-agent ops file back to create-env script 
adding the nessus agent allows for reporting
> adding back agent to create-env

- ci/pipeline.yml
- ci/update-cloud-config-tooling.sh
- fix copy errors on easta config
- backport some changes from live pipeline config
- add easta config to toolingbosh
None
> update for easta, backport running changes

- ci/pipeline.yml
- ci/update-cloud-config-tooling.yml
- add easta deployment to "all"
- map easta yaml input in tooling cloud config inputs
None
> add easta to "all" group, map easta input

- variables/master-east.yml
-add master-east-bosh vars file
-
-
None
> add master-east-bosh vars file

- ci/update-cloud-config-tooling.sh
- ci/update-cloud-config-tooling.yml
- variables/easta.yml
- variables/master-east.yml
- Clean up old east/west info
n/a
> cleanup east/west resources still left to fix pipeline

- cloud-config/cf.yml
- add tcp-routes extension
-
-
None - the tcp routes project will have security considerations, but this change itself has no implications
> add tcp-routes extension

- cloud-config/tooling.yml
- Making concourse more HA!
-
-
None
> moar AZ for concourse

- cloud-config/tooling.yml
- Network for credhub staging
-
-
None
> Concourse az

- cloud-config/tooling.yml
- Network for credhub prod
-
-
None
> credhub az

- runtime-config/runtime.yml
- add clamav mirror and alert settings
Lets us control clamav better to make it more robust
> add clamav mirror and alert settings

- runtime-config/runtime.yml
- expose more clamav variables through runtime config
None
> expose more clamav variables through runtime config

- runtime-config/runtime.yml
- allow configuring clamav scan directories
None
> allow configuring clamav scan directories

- runtime-config/runtime.yml
- allow passing directories to skip from clamav
letting us tune clamav is good for security
> allow passing directories to skip from clamav

- cloud-config/base.yml
- Specify disk for r5.large which is only used by the archivers
None
> Up the disk for archivers

- bosh-create-env.sh
- Bionic for master-bosh
- Bionic is specified for tooling/env boshes via cloud config so should be good there.
-
None
> Added bionic ops files for createenv

- runtime-config/runtime.yml
- addition of syslog to runtime config
-
-
none
> Syslog jammy

- runtime-config/runtime.yml
Resolves https://github.com/cloud-gov/product/issues/2427.
New stem cells maintain or improve platform security.
> Add node-exporter release to Jammy runtime

- runtime-config/runtime.yml
- to ensure deployment gets the runtime config applied
None
> improving runtime-config

- runtime-config/runtime.yml
- The addition didnt work so reverting
None
> removed domain broker specification

- bosh-create-env.yml
- ci/pipeline.yml
- ci/terraform-secrets.yml
- ci/update-cloud-config-tooling-development.yml
- ci/update-cloud-config-tooling.yml
- ci/update-cloud-config.yml
- ci/update-runtime-config.yml
- Update to use harden-concourse-task container
Use of hardened containers improves security
> Update pipeline and scripts to use hardened container

- ci/pipeline.yml
- runtime-config/runtime.yml
- Addition of jammy-snort release in runtime-config
- Addition of jammy-snort job in runtime-config
-
none
> Jammy snort

- ci/update-runtime-config.yml
- updating runtime-config
-
-
none
> updating runtime-config to have jammy-snort

- releases/releases.yml
- Removal of jammy snort
- addition of fisma-jammy
-
none
> addition of fisma-jammy and removal of Jammy snort

- runtime-config/runtime.yml
-fixed runtime config from _ to - for fisma jammy
-
-
none
> updating runtime config

- releases/releases.yml
- Removing admin-ui from releases
None as this is removing config for an application
> Removing admin-ui from the releases as it is being retired

- cloud-config/main.yml
- retiring admin-ui
-
-
None, retiring admin-ui
> removing more admin-ui configs

- releases/releases.yml
- update release sources to use main branch instead of master
None
> update release branches to main

- bosh-create-env.sh
- bosh-create-env.yml
- ci/pipeline.yml
- Move creds to it's own output 
not leaving secretes behind
> moving creds to it's own resource output

- ci/pipeline.yml
- operations/cron.yml
- operations/external-db.yml
- Modified the unknowm-vms.sh script in cron.yml to use awslogs-jammy and toolbelt-psql
- Added the toolbelt resource to deploy-development-bosh
- Added the toolbelt resource to be consumed in dev/staging/prod jobs
Toolbelt will be monitored for compliance and removed if any issues are found.
> Modified unkown-vms.sh to use awslogs-jammy and toolbelt-psql.

- cloud-config/staging.yml
- Updating staging to test expansion of prod disk for logsearch
-
-
None - just updating disk size
> Updating logsearch volume in staging as a test for prod

- variables/terraform-westa-hub.yml
- Adds a variables file for the new hub
-
-
None, file is rendered in a bosh int command
> Adding stub for westa-hub

- operations/ca.yml
- Add ops file overrides for protobosh usage to match what existing processes are doing
-
-
None
> Adding ca alterations ops file

- operations/external-db-protobosh.yml
- operations/s3-blobstore-protobosh.yml
- Added both blobstore and external db opsfiles for protobosh
-
-
No security issues as this has variables and no secrets
> Adding blobstore and external db for protobosh

- operations/external-db-protobosh.yml
- fixing variable in external db opsfile
-
-
No security issues as this has variables and no secrets
> fixing variable in external db opsfile

- operations/external-db-protobosh.yml
- Incorrect url used, fixed
-
-
None
> Fixed toolbelt location

- variables/westa-hub-tooling.yml
- Adding variables file for new tooling bosh director, this is one of the answer files
- Creating as a new file as to not impact existing tooling director
-
None
> Adding variables file for new tooling bosh director

- cloud-config/hub-tooling.yml
- Updated values for new hub environment for the cloud config
-
-
None
> updated values for cloud config

- cloud-config/hub-tooling.yml
- Updates for the azs etc for cloud config
None
> updates for cloud-config

- releases/releases.yml
- update to allow releases of opensearch
-
-
none
> fixing of cron and addition of opensearch

- cloud-config/cf.yml
- logstash cloud config
-
-
None
> logstash routers

- cloud-config/cf.yml
- target group is an array again
none
> More target group

- cloud-config/main.yml
- addition of opensearch profile
-
-
none
> addition of opensearch profile

- cloud-config/base.yml
- cloud-config/development.yml
- cloud-config/main.yml
- cloud-config/staging.yml
- Including values for logs_opensearch
-
-
none
> Opensearch

- cloud-config/tooling.yml
- Updates tooling cloud config with staging-defectdojo network
Adds new network to work with defect dojo
> add defectdojo to cloud config

- cloud-config/tooling.yml
- Fixes typo in defect dojo load balancer variable name
None, just fixing a typo
> Fix typo in defect dojo lb

- operations/cron.yml
- Adding whitespace inside operations folder so commit is signed by new gpg key and the pipeline git resource looks in this path
-
-
None
> New GPG Key whitespace

- cloud-config/development.yml
- cloud-config/main.yml
- 150GB to 200GB for dev
- 12TB to 17TB for prod
none
> Expand ES disk for dev and prod

- cloud-config/main.yml
- disk cant be this high
-
-
none
> gp3 disk limit

- cloud-config/main.yml
- logsearch platform is almost full in a few nodes
None
> bump logs platform disk

- cloud-config/base.yml
- Add 6 series instance types, matched up with existing 5 series in-use instance types
- Ticket: https://github.com/cloud-gov/product/issues/2934
-
None
> Add 6 series instance types

- cloud-config/development.yml
- True up disk size for `logsearch_es_data` in dev
-
-
None, changing a disk size
> True up disk size for logsearch_es_data

- bosh-create-env.sh
- Removed from upstream
-
-
None
> Remove powerdns

- empty-vm.yml
- operations/masterbosh-ntp.yml
- operations/nist-ntp.yml
- releases/releases.yml
- runtime-config/runtime.yml
- Redoing last PR due to formatting issues
- This removes all references to bionic 
- This includges removing cg-s3-fisma-release, cg-s3-snort-release and cg-s3-awslogs-bionic-release
None, removing stuff
> Removed all refs to bionic, fisma-release, snort-release and awslogs-bionic

- cloud-config/base.yml
- Adding m6i.large.concourse.web
-
-
None
> True up cloud config m6i.large.concourse.web

- ci/pipeline.yml
- Updating pipeline for removal of fisma, snort and bionic
-
-
None
> adding in missed pipeline file

- ci/pipeline.yml
- operations/nist-ntp.yml
- Updated pipeline to use the s3 version of cron
- Updated ops file to fix formatting
-
None
> update pipeline and ops file to fix missing formatting etc

- operations/update.yml
- Switch to 6i series for directors
-
-
None
> Switch to 6i series for directors

- cloud-config/cf.yml
- Instead of pointing to one target group, now it pulls a list of target groups
None
> Improve main router's target groups

- ci/pipeline.yml
- operations/s3-blobstore.yml
- Move to using bosh-deployment file instead of our own but we need some tweeks
n/a
> Moving to use bosh-deployment file with tweeks

- operations/s3-blobstore.yml
- Accidentally removed the remove step which caused an array append instead of the intended replace
n/a
> Adding back in the missing remove to s3-blobstore

- cloud-config/tooling.yml
- Adding in CC changes for concourse-pages
n/a
> Adding in assets for concourse pages

- cloud-config/tooling.yml
> Removing extra _

- cloud-config/tooling.yml
- I blindly added values when I meant to re-use existing
n/a
> bad name on value

- cloud-config/tooling.yml
- Concourse Pages is in az2
n/a
> Concourse Pages is in az2

- bosh-create-env.yml
- ci/pipeline.yml
- ci/terraform-secrets.yml
- ci/update-cloud-config-tooling-development.yml
- ci/update-cloud-config-tooling.yml
- ci/update-cloud-config.yml
- ci/update-runtime-config.yml
- Update code to use hardened images
Use hardened images
> use hardened images

- ci/pipeline.yml
- Adding missing image for terraform-task
Fixing missed image reference
> add missing image

- cloud-config/development.yml
- adjusting size to be the same
-
-
None
> adjusting sizes to be the same

- cloud-config/cf.yml
- opensearch needs a 15 for its 10.1 needs
-
-
None
> adding a 15 option

- cloud-config/main.yml
- opensearch doesn't use this
-
-
None
> removing elb

- releases/releases.yml
Add the wazuh agent bosh release to the releases pipeline
New bosh release needed for compliance.
> add wazuh agent

- cloud-config/tooling.yml
- Add cloud-config settings for development defectdojo
Adding new cloud-config settings for development defectdojo
> add development defectdojo

- cloud-config/main.yml
- We are now storing more logs for longer for internal usage
-
-
None
> Bump logsearch platform disk

- cloud-config/tooling.yml
- Adds production defectdojo to cloud config
Adding production defectdojo
> update cloud config for prod defectdojo

- cloud-config/main.yml
> bump ready for next os deploy

- cloud-config/development.yml
- Bump dev logsearch platform data disk form 200 -> 250
n/a
> Upping dev logsearch platform disk

- cloud-config/development.yml
- cloud-config/main.yml
- cloud-config/staging.yml
> adding in new disk for opensearch old data nodes

- cloud-config/main.yml
- New disk type for platform logs
-
-
saving monehs!
> Adding warm disk type for logsearch
